import { jsPDF } from 'jspdf';

interface MedicalRecord {
    date: string;
    treatment: string;
    notes: string;
    satisfaction: number;
}

interface SummaryData {
    patientName: string;
    age: number;
    gender: string;
    records: MedicalRecord[];
}

export const generateSummaryPDF = (data: SummaryData) => {
    const doc = new jsPDF();

    // Branding Colors
    const deepNavy = [15, 23, 42]; // #0f172a
    const roseGold = [183, 110, 121]; // #b76e79

    // Header
    doc.setFillColor(deepNavy[0], deepNavy[1], deepNavy[2]);
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 240);
    doc.setFont("serif", "bold");
    doc.setFontSize(22);
    doc.text("OMNI AESTHETIX", 20, 25);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("MEDICAL TREATMENT SUMMARY", 20, 32);

    // Border
    doc.setDrawColor(roseGold[0], roseGold[1], roseGold[2]);
    doc.setLineWidth(1);
    doc.line(0, 40, 210, 40);

    // Patient Info
    doc.setTextColor(deepNavy[0], deepNavy[1], deepNavy[2]);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("PATIENT PROFILE", 20, 55);

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text(`Name: ${data.patientName}`, 20, 65);
    doc.text(`Age: ${data.age} yrs`, 20, 72);
    doc.text(`Gender: ${data.gender}`, 20, 79);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 140, 65);

    // Divider
    doc.setDrawColor(240, 240, 240);
    doc.line(20, 85, 190, 85);

    // Treatment Log
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("TREATMENT LOG", 20, 95);

    let y = 105;
    data.records.forEach((record, index) => {
        // Check for page break
        if (y > 250) {
            doc.addPage();
            y = 20;
        }

        // Card-like structure
        doc.setFillColor(252, 252, 252);
        doc.rect(20, y, 170, 35, 'F');
        doc.setDrawColor(230, 230, 230);
        doc.rect(20, y, 170, 35, 'S');

        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.text(`${record.date} - ${record.treatment}`, 25, y + 8);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(100, 100, 100);
        const splitNotes = doc.splitTextToSize(record.notes, 160);
        doc.text(splitNotes, 25, y + 15);

        doc.setTextColor(roseGold[0], roseGold[1], roseGold[2]);
        doc.text(`Patient Satisfaction Score: ${record.satisfaction}/10`, 25, y + 30);

        y += 42;
        doc.setTextColor(deepNavy[0], deepNavy[1], deepNavy[2]);
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("This is an automated summary generated by Omni AesthetiX Precision CRM.", 105, 285, { align: "center" });

    // Page Border
    doc.setDrawColor(roseGold[0], roseGold[1], roseGold[2]);
    doc.setLineWidth(0.5);
    doc.rect(5, 5, 200, 287);

    doc.save(`${data.patientName}_Treatment_Summary.pdf`);
};
