/**
 * Utility to generate a WhatsApp wa.me link with a pre-filled message.
 * @param phone - Patient's phone number
 * @param message - The text message draft generated by AI
 */
export function generateWhatsAppLink(phone: string, message: string): string {
    // Sanitize phone number: remove non-numeric characters
    const sanitizedPhone = phone.replace(/\D/g, "");

    // Ensure Indonesian phone numbers start with 62
    let finalPhone = sanitizedPhone;
    if (finalPhone.startsWith("0")) {
        finalPhone = "62" + finalPhone.substring(1);
    } else if (!finalPhone.startsWith("62")) {
        finalPhone = "62" + finalPhone;
    }

    const encodedMessage = encodeURIComponent(message);
    return `https://wa.me/${finalPhone}?text=${encodedMessage}`;
}
